services:
  entity.factory:
    synthetic: true
  entity.factory.event:
    class: \Vainyl\Entity\Operation\Decorator\EventEntityOperationFactoryDecorator
    decorates: entity.factory
    decoration_priority: 1000
    arguments: ['@entity.factory.event.inner', '@collection.factory.sequence', '@event.dispatcher.collection']