services:
  database.document:
    synthetic: true
  entity.hydrator:
    synthetic: true
  entity.operation.factory:
    synthetic: true
  entity.operation.factory.event:
    class: Vainyl\Entity\Operation\Decorator\EventEntityOperationFactoryDecorator
    decorates: entity.operation.factory
    decoration_priority: 1000
    arguments: ['@entity.operation.factory.event.inner', '@collection.factory.sequence', '@event.dispatcher.collection']