services:
  entity.operation.factory.event:
    class: Vainyl\Entity\Operation\Decorator\EventEntityOperationFactoryDecorator
    decorates: entity.operation.factory
    decoration_priority: 1000
    arguments: ['@entity.operation.factory.event.inner', '@collection.factory.sequence', '@event.dispatcher.collection']
  entity.operation.factory.timestamp:
    class: Vainyl\Entity\Operation\Decorator\TimestampEntityOperationFactoryDecorator
    decorates: entity.operation.factory
    decoration_priority: 100
    arguments: ['@entity.operation.factory.timestamp.inner', '@collection.factory.sequence', '@time.provider']